### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-FISH#9]
@Mava04, I think I have a running version now, could you please try to install and run it accord to these instructions? https://github.com/tischi/fiji-plugin-FISH/blob/master/README.md#installation

**Comment by Mava04** [comment]
@tischi, I followed your instructions. However, I cannot install the plugin, and I am not getting any error message. What might have gone wrong?

**Comment by Mava04** [comment]
@tischi The plugin is not listed in the window with the plugins that may be installed or updated

**Comment by tischi** [comment]
OK! Let's try to figure it out:

1. are you sure you checked the update site EMBL-CBA ?
1. can you check whether the plugin is within your jars folder? For me it looks like this:
```
tischer@Christians-MBP ~ $ ls /Applications/Fiji.app/jars/fiji-plugin-*
-rw-r--r--  1 tischer  staff    39K Apr  9 16:00 /Applications/Fiji.app/jars/fiji-plugin-FISH-0.1.0.jar
-rw-r--r--  1 tischer  staff   559K Mar 25 08:35 /Applications/Fiji.app/jars/fiji-plugin-bigDataProcessor2-0.3.10.jar
-rw-r--r--  1 tischer  staff   269K Apr  4 16:12 /Applications/Fiji.app/jars/fiji-plugin-cats-0.7.3.jar
-rw-r--r--  1 tischer  staff    50K Apr  3 10:04 /Applications/Fiji.app/jars/fiji-plugin-elastixWrapper-0.4.3.jar
-rw-r--r--  1 tischer  staff    12K Oct 29 07:44 /Applications/Fiji.app/jars/fiji-plugin-granulometry-0.1.0.jar
-rw-r--r--  1 tischer  staff    84K Oct 29 07:44 /Applications/Fiji.app/jars/fiji-plugin-illuminationCorrection-0.1.03.jar
-rw-r--r--  1 tischer  staff   118K Oct 29 07:44 /Applications/Fiji.app/jars/fiji-plugin-imageRegistration-0.5.14.jar
-rw-r--r--  1 tischer  staff   8.8K Oct 29 07:44 /Applications/Fiji.app/jars/fiji-plugin-lazyRatioViewer-0.1.0.jar
-rw-r--r--  1 tischer  staff   240K Apr  4 15:41 /Applications/Fiji.app/jars/fiji-plugin-morphometry-0.5.2.jar
-rw-r--r--  1 tischer  staff    76K Oct 29 07:45 /Applications/Fiji.app/jars/fiji-plugin-multiTemplateMatching-0.4.0.jar
-rw-r--r--  1 tischer  staff    96K Oct 29 07:44 /Applications/Fiji.app/jars/fiji-plugin-plateViewer-0.2.23.jar
-rw-r--r--  1 tischer  staff    85K Mar  1 12:45 /Applications/Fiji.app/jars/fiji-plugin-platynereisViewer-0.5.8.jar
-rw-r--r--  1 tischer  staff    12K Oct 29 07:44 /Applications/Fiji.app/jars/fiji-plugin-yamlMetadataCreator-0.1.07.jar
```

with **fiji-plugin-FISH-0.1.0.jar** present.

**Comment by Mava04** [comment]
@tischi, Yes, EMBL-CBA is ticked and the jar file is there. There was also an update today. However, I still cannot find the plugin when I open ImageJ.

**Comment by tischi** [comment]
Are you sure you are looking in the right place? 
I moved it from EMBL to Analyze:  **[ Plugins > Analyze > FISH Spots ]**

**Comment by Mava04** [comment]
I checked basically everywhere, and first of all in Analyze. It's strange. Might it be that there are some issues with other packages, apart from the open-stacks-as-virtualstacks? Anyway, I'll check again when I'm back home, just to be totally sureInviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: tischi <notifications@github.com> Data: 11/04/20  17:16  (GMT+01:00) A: tischi/fiji-plugin-FISH <fiji-plugin-FISH@noreply.github.com> Cc: Mava04 <martinavarisco95@gmail.com>, Mention <mention@noreply.github.com> Oggetto: Re: [tischi/fiji-plugin-FISH] Installation (#9) 
Are you sure you are looking in the right place?
I moved it from EMBL to Analyze:  [ Plugins > Analyze > FISH Spots ]

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tischi/fiji-plugin-FISH/issues/9#issuecomment-612443931",
"url": "https://github.com/tischi/fiji-plugin-FISH/issues/9#issuecomment-612443931",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tischi** [comment]
ok. let me know. if it does not work like this, I can try something else.

**Comment by Mava04** [comment]
@tischi Bad news, I still cannot see the plugin. It's in the jar folder, but I cannot find it anywhere in ImageJ. Re-installing Fiji did not solve the issue.

**Comment by tischi** [comment]
seems to work now.
